// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr2OspjiIyptjyctE0MNkXsNn6-HZS5so',
    appId: '1:71018655731:android:4478b3b8d85f24d1df6c86',
    messagingSenderId: '71018655731',
    projectId: 'kitahack-aac',
    databaseURL: 'https://kitahack-aac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitahack-aac.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGnWnsE1x513TJLPbO9n0t0HKbhYrJXcY',
    appId: '1:71018655731:ios:985b8057859d88a7df6c86',
    messagingSenderId: '71018655731',
    projectId: 'kitahack-aac',
    databaseURL: 'https://kitahack-aac-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'kitahack-aac.firebasestorage.app',
    iosBundleId: 'com.example.spectrumLink',
  );
}
